services:
  mongo:
    image: mongo:8.0.3
    container_name: sf-db
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js