name: "Issue Milestone Management"

on:
  issues:
    types: [labeled, closed]

jobs:
  manage-milestone:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Add "High Priority" milestone to issues with "P1" label
        if: github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'P1')
        run: |
          node --input-type=module -e "
            import { Octokit } from '@octokit/rest';
            import { context } from '@actions/github';
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            await octokit.issues.update({
              owner,
              repo,
              issue_number,
              milestone: 'High Priority'
            });
          "

      - name: Remove "High Priority" milestone from closed issues
        if: github.event.action == 'closed' && contains(github.event.issue.labels.*.name, 'P1')
        run: |
          node --input-type=module -e "
            import { Octokit } from '@octokit/rest';
            import { context } from '@actions/github';
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            await octokit.issues.update({
              owner,
              repo,
              issue_number,
              milestone: null
            });
          "